FROM alpine:3.20
LABEL maintainer="Danil Lukinykh <danluki02@yandex.ru>"

RUN set -x \
	&& buildDeps='bash ca-certificates openssl tzdata' \
	&& apk add --no-cache --update $buildDeps

EXPOSE 8080 8946

ENV SHELL /bin/bash
COPY * /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/taskvault"]

CMD ["--help"]