FROM alpine:3.20
LABEL maintainer="Danil Lukinykh <danluki02@yandex.ru>"

RUN set -x \
    && apk add --no-cache --update \
       bash ca-certificates openssl tzdata libc6-compat

EXPOSE 8080 8946

ENV SHELL /bin/bash

COPY ./bin/syncra /usr/local/bin/

CMD ["/usr/local/bin/syncra"]