services:
  taskvault:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
      - "8946"
      - "6868:6868"
    environment:
      - GODEBUG=netdns=go
    command: syncra agent --server --log-level=debug --bootstrap-expect=1 --node-name=taskvault1
  taskvault-server1:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8081:8080"
      - "8946"
      - "6869:6868"
    environment:
      - GODEBUG=netdns=go
    command: syncra agent --server --retry-join=taskvault:8946 --log-level=debug --bootstrap-expect=3  --node-name=taskvault2 --tag server=2
  taskvault-server2:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8082:8080"
      - "8946"
      - "6870:6868"
    environment:
      - GODEBUG=netdns=go
    command: syncra agent --server --retry-join=taskvault:8946 --log-level=debug  --node-name=taskvault3 --tag server=2

