# Default values for taskvault. Replace this based on your needs.
image:
  repository: danluki/taskvault
  pullPolicy: Always
  tag: ""
  pullSecretName: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

server:
  replicaCount: 3

  log:
    level: "info"

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 8080

  resources: {}
  autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}
  persistence:
    size: 1Gi

envs: {}