apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 4321
      targetPort: 4321
      nodePort: 30421
  type: {{ .Values.service.type }}