apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taskvault.fullname" . }}-server
  labels:
    {{- include "taskvault.serverLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "taskvault.serverSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.server.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.image.pullPolicy "Always" }}
        uuid: {{ uuidv4 }}
      {{- end }}
      labels:
        {{- include "taskvault.serverSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "taskvault.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/syncra"]
          args:
            - "agent"
            - "--server"
            - "--config=/etc/syncra/syncra.yaml"
            - "--data-dir=/syncra"
            - "--retry-join=\"provider=k8s label_selector=\"\"app.kubernetes.io/instance={{ .Release.Name }}\"\" namespace=\"\"{{ .Release.Namespace }}\"\"\""
            - "--log-level={{ .Values.server.log.level }}"
            - "--bootstrap-expect=1"
          ports:
            -   name: serf
                containerPort: 8946
            -   name: grpc
                containerPort: 6868
            -   name: http
                containerPort: 8080
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "taskvault.fullname" . }}-envs
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}