{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "taskvault.serviceAccountName" . }}
  labels:
    {{- include "taskvault.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{ if .Values.image.pullSecretName -}}
imagePullSecrets:
  - name: {{ .Values.image.pullSecretName }}
{{- end }}