apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskvault.fullname" . }}
  labels:
    {{- include "taskvault.serverLabels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  clusterIP: None
  # Servers have to be available even they aren't ready
  # because they need to join the cluster
  publishNotReadyAddresses: true
  ports:
    - protocol: TCP
      name: serf
      port: 8946
    - protocol: TCP
      name: grpc
      port: 6868
    - protocol: TCP
      name: web
      port: 8080
  selector:
    {{- include "taskvault.serverSelectorLabels" . | nindent 4 }}