apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "taskvault.fullname" . }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "taskvault.serverSelectorLabels" . | nindent 6 }}