services:
  taskvault:
    build: ..
    ports:
      - "8080:8080"
      - "8946"
      - "6868:6868"
    environment:
      - GODEBUG=netdns=go
    command: taskvault agent --server --log-level=debug --bootstrap-expect=1 --node-name=taskvault1
  taskvault-server1:
    build: ..
    ports:
      - "8081:8080"
      - "8946"
      - "6869:6868"
    environment:
      - GODEBUG=netdns=go
    command: taskvault agent --server --retry-join=taskvault:8946 --log-level=debug --bootstrap-expect=3  --node-name=taskvault2 --tag server=2
  taskvault-server2:
    build: ..
    ports:
      - "8082:8080"
      - "8946"
      - "6870:6868"
    environment:
      - GODEBUG=netdns=go
    command: taskvault agent --server --retry-join=taskvault:8946 --log-level=debug  --node-name=taskvault3 --tag server=2
  taskvault-docs:
    build:
      context: ..
      dockerfile: ../Dockerfile.docs
    container_name: astro-docs
    ports:
      - "4321:4321"
    volumes:
      - ./docs:/app  # Mount local docs folder
    restart: unless-stopped
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
#  grafana:
#    image: grafana/grafana
#    ports:
#      - "3000:3000"
